apiVersion: apps/v1
kind: Deployment
metadata:
  name: app112
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app112
  template:
    metadata:
      labels:
        app: app112
      name: app112
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app112
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
