apiVersion: apps/v1
kind: Deployment
metadata:
  name: app107
spec:
  replicas: 7
  selector:
    matchLabels:
      app: app107
  template:
    metadata:
      labels:
        app: app107
      name: app107
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app107
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
