apiVersion: apps/v1
kind: Deployment
metadata:
  name: app108
spec:
  replicas: 6
  selector:
    matchLabels:
      app: app108
  template:
    metadata:
      labels:
        app: app108
      name: app108
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app108
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
