apiVersion: apps/v1
kind: Deployment
metadata:
  name: app11
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app11
  template:
    metadata:
      labels:
        app: app11
      name: app11
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - app23
            topologyKey: kubernetes.io/hostname
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app11
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
