apiVersion: apps/v1
kind: Deployment
metadata:
  name: app104
spec:
  replicas: 5
  selector:
    matchLabels:
      app: app104
  template:
    metadata:
      labels:
        app: app104
      name: app104
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - app82
            topologyKey: kubernetes.io/hostname
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app104
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
