apiVersion: apps/v1
kind: Deployment
metadata:
  name: app106
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app106
  template:
    metadata:
      labels:
        app: app106
      name: app106
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app106
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
