apiVersion: apps/v1
kind: Deployment
metadata:
  name: app113
spec:
  replicas: 6
  selector:
    matchLabels:
      app: app113
  template:
    metadata:
      labels:
        app: app113
      name: app113
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app113
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
