apiVersion: apps/v1
kind: Deployment
metadata:
  name: app118
spec:
  replicas: 8
  selector:
    matchLabels:
      app: app118
  template:
    metadata:
      labels:
        app: app118
      name: app118
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app118
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
