apiVersion: apps/v1
kind: Deployment
metadata:
  name: app16
spec:
  replicas: 8
  selector:
    matchLabels:
      app: app16
  template:
    metadata:
      labels:
        app: app16
      name: app16
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app16
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
