apiVersion: apps/v1
kind: Deployment
metadata:
  name: app13
spec:
  replicas: 10
  selector:
    matchLabels:
      app: app13
  template:
    metadata:
      labels:
        app: app13
      name: app13
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - app46
            topologyKey: kubernetes.io/hostname
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app13
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
