apiVersion: apps/v1
kind: Deployment
metadata:
  name: app119
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app119
  template:
    metadata:
      labels:
        app: app119
      name: app119
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: NotIn
                values:
                - app15
            topologyKey: kubernetes.io/hostname
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app119
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
