apiVersion: apps/v1
kind: Deployment
metadata:
  name: app105
spec:
  replicas: 10
  selector:
    matchLabels:
      app: app105
  template:
    metadata:
      labels:
        app: app105
      name: app105
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - app113
            topologyKey: kubernetes.io/hostname
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app105
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
