apiVersion: apps/v1
kind: Deployment
metadata:
  name: app109
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app109
  template:
    metadata:
      labels:
        app: app109
      name: app109
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - app91
                - app119
            topologyKey: kubernetes.io/hostname
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app109
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
