apiVersion: apps/v1
kind: Deployment
metadata:
  name: app111
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app111
  template:
    metadata:
      labels:
        app: app111
      name: app111
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app111
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
