apiVersion: apps/v1
kind: Deployment
metadata:
  name: app103
spec:
  replicas: 7
  selector:
    matchLabels:
      app: app103
  template:
    metadata:
      labels:
        app: app103
      name: app103
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app103
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
