apiVersion: apps/v1
kind: Deployment
metadata:
  name: app14
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app14
  template:
    metadata:
      labels:
        app: app14
      name: app14
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app14
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
