apiVersion: apps/v1
kind: Deployment
metadata:
  name: app115
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app115
  template:
    metadata:
      labels:
        app: app115
      name: app115
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app115
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
