apiVersion: apps/v1
kind: Deployment
metadata:
  name: app12
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app12
  template:
    metadata:
      labels:
        app: app12
      name: app12
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app12
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
