apiVersion: apps/v1
kind: Deployment
metadata:
  name: app15
spec:
  replicas: 11
  selector:
    matchLabels:
      app: app15
  template:
    metadata:
      labels:
        app: app15
      name: app15
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app15
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
