apiVersion: apps/v1
kind: Deployment
metadata:
  name: app10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app10
  template:
    metadata:
      labels:
        app: app10
      name: app10
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app10
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
