apiVersion: apps/v1
kind: Deployment
metadata:
  name: app116
spec:
  replicas: 10
  selector:
    matchLabels:
      app: app116
  template:
    metadata:
      labels:
        app: app116
      name: app116
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app116
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
