apiVersion: apps/v1
kind: Deployment
metadata:
  name: app101
spec:
  replicas: 11
  selector:
    matchLabels:
      app: app101
  template:
    metadata:
      labels:
        app: app101
      name: app101
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app101
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
