apiVersion: apps/v1
kind: Deployment
metadata:
  name: app102
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app102
  template:
    metadata:
      labels:
        app: app102
      name: app102
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app102
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
