apiVersion: apps/v1
kind: Deployment
metadata:
  name: app25
spec:
  replicas: 10
  selector:
    matchLabels:
      app: app25
  template:
    metadata:
      labels:
        app: app25
      name: app25
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app25
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
