apiVersion: apps/v1
kind: Deployment
metadata:
  name: app26
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app26
  template:
    metadata:
      labels:
        app: app26
      name: app26
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app26
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
