apiVersion: apps/v1
kind: Deployment
metadata:
  name: app22
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app22
  template:
    metadata:
      labels:
        app: app22
      name: app22
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app22
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
