apiVersion: apps/v1
kind: Deployment
metadata:
  name: app21
spec:
  replicas: 8
  selector:
    matchLabels:
      app: app21
  template:
    metadata:
      labels:
        app: app21
      name: app21
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app21
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
