apiVersion: apps/v1
kind: Deployment
metadata:
  name: app23
spec:
  replicas: 9
  selector:
    matchLabels:
      app: app23
  template:
    metadata:
      labels:
        app: app23
      name: app23
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app23
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
