apiVersion: apps/v1
kind: Deployment
metadata:
  name: app28
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app28
  template:
    metadata:
      labels:
        app: app28
      name: app28
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - app32
            topologyKey: kubernetes.io/hostname
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app28
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
