apiVersion: apps/v1
kind: Deployment
metadata:
  name: app38
spec:
  replicas: 8
  selector:
    matchLabels:
      app: app38
  template:
    metadata:
      labels:
        app: app38
      name: app38
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app38
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
