apiVersion: apps/v1
kind: Deployment
metadata:
  name: app30
spec:
  replicas: 8
  selector:
    matchLabels:
      app: app30
  template:
    metadata:
      labels:
        app: app30
      name: app30
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - app64
                - app117
            topologyKey: kubernetes.io/hostname
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app30
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
