apiVersion: apps/v1
kind: Deployment
metadata:
  name: app37
spec:
  replicas: 8
  selector:
    matchLabels:
      app: app37
  template:
    metadata:
      labels:
        app: app37
      name: app37
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app37
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
