apiVersion: apps/v1
kind: Deployment
metadata:
  name: app33
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app33
  template:
    metadata:
      labels:
        app: app33
      name: app33
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app33
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
