apiVersion: apps/v1
kind: Deployment
metadata:
  name: app35
spec:
  replicas: 8
  selector:
    matchLabels:
      app: app35
  template:
    metadata:
      labels:
        app: app35
      name: app35
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - app35
            topologyKey: kubernetes.io/hostname
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app35
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
