apiVersion: apps/v1
kind: Deployment
metadata:
  name: app32
spec:
  replicas: 11
  selector:
    matchLabels:
      app: app32
  template:
    metadata:
      labels:
        app: app32
      name: app32
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app32
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
