apiVersion: apps/v1
kind: Deployment
metadata:
  name: app44
spec:
  replicas: 7
  selector:
    matchLabels:
      app: app44
  template:
    metadata:
      labels:
        app: app44
      name: app44
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: NotIn
                values:
                - app33
              - key: app
                operator: In
                values:
                - app103
            topologyKey: kubernetes.io/hostname
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app44
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
