apiVersion: apps/v1
kind: Deployment
metadata:
  name: app48
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app48
  template:
    metadata:
      labels:
        app: app48
      name: app48
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app48
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
