apiVersion: apps/v1
kind: Deployment
metadata:
  name: app45
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app45
  template:
    metadata:
      labels:
        app: app45
      name: app45
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app45
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
