apiVersion: apps/v1
kind: Deployment
metadata:
  name: app4
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app4
  template:
    metadata:
      labels:
        app: app4
      name: app4
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app4
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
