apiVersion: apps/v1
kind: Deployment
metadata:
  name: app41
spec:
  replicas: 5
  selector:
    matchLabels:
      app: app41
  template:
    metadata:
      labels:
        app: app41
      name: app41
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - app74
            topologyKey: kubernetes.io/hostname
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app41
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
