apiVersion: apps/v1
kind: Deployment
metadata:
  name: app42
spec:
  replicas: 6
  selector:
    matchLabels:
      app: app42
  template:
    metadata:
      labels:
        app: app42
      name: app42
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app42
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
