apiVersion: apps/v1
kind: Deployment
metadata:
  name: app40
spec:
  replicas: 11
  selector:
    matchLabels:
      app: app40
  template:
    metadata:
      labels:
        app: app40
      name: app40
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - app55
            topologyKey: kubernetes.io/hostname
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app40
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
