apiVersion: apps/v1
kind: Deployment
metadata:
  name: app52
spec:
  replicas: 6
  selector:
    matchLabels:
      app: app52
  template:
    metadata:
      labels:
        app: app52
      name: app52
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app52
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
