apiVersion: apps/v1
kind: Deployment
metadata:
  name: app51
spec:
  replicas: 10
  selector:
    matchLabels:
      app: app51
  template:
    metadata:
      labels:
        app: app51
      name: app51
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app51
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
