apiVersion: apps/v1
kind: Deployment
metadata:
  name: app50
spec:
  replicas: 6
  selector:
    matchLabels:
      app: app50
  template:
    metadata:
      labels:
        app: app50
      name: app50
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - app46
              - key: app
                operator: In
                values:
                - app90
            topologyKey: kubernetes.io/hostname
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app50
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
