apiVersion: apps/v1
kind: Deployment
metadata:
  name: app56
spec:
  replicas: 6
  selector:
    matchLabels:
      app: app56
  template:
    metadata:
      labels:
        app: app56
      name: app56
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app56
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
