apiVersion: apps/v1
kind: Deployment
metadata:
  name: app57
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app57
  template:
    metadata:
      labels:
        app: app57
      name: app57
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app57
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
