apiVersion: apps/v1
kind: Deployment
metadata:
  name: app58
spec:
  replicas: 11
  selector:
    matchLabels:
      app: app58
  template:
    metadata:
      labels:
        app: app58
      name: app58
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app58
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
