apiVersion: apps/v1
kind: Deployment
metadata:
  name: app59
spec:
  replicas: 10
  selector:
    matchLabels:
      app: app59
  template:
    metadata:
      labels:
        app: app59
      name: app59
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app59
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
