apiVersion: apps/v1
kind: Deployment
metadata:
  name: app54
spec:
  replicas: 10
  selector:
    matchLabels:
      app: app54
  template:
    metadata:
      labels:
        app: app54
      name: app54
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app54
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
