apiVersion: apps/v1
kind: Deployment
metadata:
  name: app67
spec:
  replicas: 9
  selector:
    matchLabels:
      app: app67
  template:
    metadata:
      labels:
        app: app67
      name: app67
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app67
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
