apiVersion: apps/v1
kind: Deployment
metadata:
  name: app63
spec:
  replicas: 10
  selector:
    matchLabels:
      app: app63
  template:
    metadata:
      labels:
        app: app63
      name: app63
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - app37
            topologyKey: kubernetes.io/hostname
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - app83
            topologyKey: kubernetes.io/hostname
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app63
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
