apiVersion: apps/v1
kind: Deployment
metadata:
  name: app65
spec:
  replicas: 5
  selector:
    matchLabels:
      app: app65
  template:
    metadata:
      labels:
        app: app65
      name: app65
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - app112
            topologyKey: kubernetes.io/hostname
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app65
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
