apiVersion: apps/v1
kind: Deployment
metadata:
  name: app62
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app62
  template:
    metadata:
      labels:
        app: app62
      name: app62
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - app67
            topologyKey: kubernetes.io/hostname
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app62
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
