apiVersion: apps/v1
kind: Deployment
metadata:
  name: app64
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app64
  template:
    metadata:
      labels:
        app: app64
      name: app64
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app64
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
