apiVersion: apps/v1
kind: Deployment
metadata:
  name: app68
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app68
  template:
    metadata:
      labels:
        app: app68
      name: app68
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app68
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
