apiVersion: apps/v1
kind: Deployment
metadata:
  name: app6
spec:
  replicas: 7
  selector:
    matchLabels:
      app: app6
  template:
    metadata:
      labels:
        app: app6
      name: app6
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app6
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
