apiVersion: apps/v1
kind: Deployment
metadata:
  name: app74
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app74
  template:
    metadata:
      labels:
        app: app74
      name: app74
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - app118
            topologyKey: kubernetes.io/hostname
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app74
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
