apiVersion: apps/v1
kind: Deployment
metadata:
  name: app76
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app76
  template:
    metadata:
      labels:
        app: app76
      name: app76
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app76
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
