apiVersion: apps/v1
kind: Deployment
metadata:
  name: app77
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app77
  template:
    metadata:
      labels:
        app: app77
      name: app77
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - app16
            topologyKey: kubernetes.io/hostname
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app77
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
