apiVersion: apps/v1
kind: Deployment
metadata:
  name: app75
spec:
  replicas: 11
  selector:
    matchLabels:
      app: app75
  template:
    metadata:
      labels:
        app: app75
      name: app75
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - app24
            topologyKey: kubernetes.io/hostname
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app75
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
