apiVersion: apps/v1
kind: Deployment
metadata:
  name: app72
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app72
  template:
    metadata:
      labels:
        app: app72
      name: app72
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app72
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
