apiVersion: apps/v1
kind: Deployment
metadata:
  name: app70
spec:
  replicas: 10
  selector:
    matchLabels:
      app: app70
  template:
    metadata:
      labels:
        app: app70
      name: app70
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app70
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
