apiVersion: apps/v1
kind: Deployment
metadata:
  name: app82
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app82
  template:
    metadata:
      labels:
        app: app82
      name: app82
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app82
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
