apiVersion: apps/v1
kind: Deployment
metadata:
  name: app89
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app89
  template:
    metadata:
      labels:
        app: app89
      name: app89
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - app47
            topologyKey: kubernetes.io/hostname
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app89
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
