apiVersion: apps/v1
kind: Deployment
metadata:
  name: app87
spec:
  replicas: 10
  selector:
    matchLabels:
      app: app87
  template:
    metadata:
      labels:
        app: app87
      name: app87
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: NotIn
                values:
                - app40
            topologyKey: kubernetes.io/hostname
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app87
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
