apiVersion: apps/v1
kind: Deployment
metadata:
  name: app8
spec:
  replicas: 6
  selector:
    matchLabels:
      app: app8
  template:
    metadata:
      labels:
        app: app8
      name: app8
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - app11
            topologyKey: kubernetes.io/hostname
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app8
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
