apiVersion: apps/v1
kind: Deployment
metadata:
  name: app83
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app83
  template:
    metadata:
      labels:
        app: app83
      name: app83
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - app77
            topologyKey: kubernetes.io/hostname
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app83
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
