apiVersion: apps/v1
kind: Deployment
metadata:
  name: app84
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app84
  template:
    metadata:
      labels:
        app: app84
      name: app84
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app84
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
