apiVersion: apps/v1
kind: Deployment
metadata:
  name: app97
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app97
  template:
    metadata:
      labels:
        app: app97
      name: app97
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app97
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
