apiVersion: apps/v1
kind: Deployment
metadata:
  name: app90
spec:
  replicas: 9
  selector:
    matchLabels:
      app: app90
  template:
    metadata:
      labels:
        app: app90
      name: app90
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - app15
            topologyKey: kubernetes.io/hostname
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app90
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
