apiVersion: apps/v1
kind: Deployment
metadata:
  name: app95
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app95
  template:
    metadata:
      labels:
        app: app95
      name: app95
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app95
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
