apiVersion: apps/v1
kind: Deployment
metadata:
  name: app98
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app98
  template:
    metadata:
      labels:
        app: app98
      name: app98
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - app30
            topologyKey: kubernetes.io/hostname
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app98
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
