apiVersion: apps/v1
kind: Deployment
metadata:
  name: app99
spec:
  replicas: 5
  selector:
    matchLabels:
      app: app99
  template:
    metadata:
      labels:
        app: app99
      name: app99
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app99
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
