apiVersion: apps/v1
kind: Deployment
metadata:
  name: app92
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app92
  template:
    metadata:
      labels:
        app: app92
      name: app92
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app92
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
