apiVersion: apps/v1
kind: Deployment
metadata:
  name: app91
spec:
  replicas: 9
  selector:
    matchLabels:
      app: app91
  template:
    metadata:
      labels:
        app: app91
      name: app91
    spec:
      containers:
      - image: registry.k8s.io/pause:2.0
        name: app91
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
