apiVersion: v1
kind: Pod
metadata:
  name: S0
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - S3
          - key: app
            operator: NotIn
            values:
            - S4
            - S6
        topologyKey: topology.kubernetes.io/hostname
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - S0
        topologyKey: topology.kubernetes.io/hostname
  containers:
  - name: S0
    image: registry.k8s.io/pause:2.