apiVersion: v1
kind: Pod
metadata:
  name: S1
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - S3
        topologyKey: topology.kubernetes.io/hostname
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - S2
        topologyKey: topology.kubernetes.io/hostname
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - S0
        topologyKey: topology.kubernetes.io/hostname
  containers:
  - name: S1
    image: registry.k8s.io/pause:2.0
